### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by ndechesne** [twoerner/oe-layerindex-config#2]
I was trying to use this tool, I could pick 'master' branch, then 'beaglebone', then it would hang for a few seconds and gives me this trace:

Cloning into '/work/oe/oebuild/layers/meta-yocto'...
remote: Counting objects: 8097, done.
remote: Compressing objects: 100% (2040/2040), done.
remote: Total 8097 (delta 5105), reused 7981 (delta 4989)
Receiving objects: 100% (8097/8097), 1.03 MiB | 450.00 KiB/s, done.
Resolving deltas: 100% (5105/5105), done.
Checking connectivity... done.
Adding layer "meta-yocto-bsp" to conf/bblayers.conf
Adding layer "meta" to conf/bblayers.conf
Traceback (most recent call last):
  File "/work/oe/oe-layerindex-config/pysetup-int.py", line 181, in <module>
    code, tag = d.menu("Please choose a distro:", height=0, width=0, menu_height=0, choices=choices)
  File "/usr/lib/python2.7/dist-packages/dialog.py", line 2899, in menu
    cmd, kwargs, strip_xdialog_newline=True)
  File "/usr/lib/python2.7/dist-packages/dialog.py", line 1746, in _widget_with_string_output
    code, output = self._perform(args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dialog.py", line 1538, in _perform
    *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dialog.py", line 1299, in _call_program
    cmdargs = self.dash_escape_nf(cmdargs)
  File "/usr/lib/python2.7/dist-packages/dialog.py", line 1093, in dash_escape_nf
    return _dash_escape_nf(args)
  File "/usr/lib/python2.7/dist-packages/dialog.py", line 323, in _dash_escape_nf
    l = _dash_escape(args[1:])
  File "/usr/lib/python2.7/dist-packages/dialog.py", line 306, in _dash_escape
    if arg.startswith("--"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

**Comment by twoerner** [comment]
Thanks for your report and thanks for trying this tool!

Out of curiosity, which "beaglebone" did you pick? There are three:
    beaglebone:meta-ti
    beaglebone: meta-yocto-bsp
    beaglebon: meta-beagleboard

Can I assume you're using:
    arch
    some sort of gnome-terminal
?

**Comment by twoerner** [comment]
Oh wait, that stuff probably doesn't matter.

The next screen the program was trying to show you includes the distro list. That list includes "Ångström", I'm betting this might be another case of some additional package required.

**Comment by twoerner** [comment]
Hmm... I can't reproduce this. Using a fresh install of OpenSUSE 13.2 (in a VM) both with xterm and konsole. Install all prerequisites, source the script... and I'm able to get to the end without problem.
